#!/bin/sh
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master

class=`git config zephyr.class`
instance=`git config zephyr.instance`
zsig=`git config zephyr.zsig`
color=`git config --bool zephyr.color`

if [ "${color:-true}" = "true" ]; then
    usecolor="--color"
else
    usecolor=""
fi

if [ -z "$zsig" ]; then
    if [ -e "$GIT_DIR/description" ]; then
        zsig=`cat "$GIT_DIR/description"`
    fi
    if [ -z "$zsig" ] || \
        [ "$zsig" = "Unnamed repository; edit this file to name it for gitweb." ] || \
        [ "$zsig" = "Unnamed repository; edit this file 'description' to name the repository." ]; then
        zsig=$(basename "$(readlink -f "$GIT_DIR")")
        if [ "$zsig" = ".git" ]; then
            zsig=$(basename "$(readlink -f "$GIT_DIR/..")")
        fi
    fi
fi

if [ -z "$class" ]; then
  echo "I don't know where to send a commit zephyr!" >&2
  echo "Please set the zephyr.class config variable in" >&2
  echo "$PWD/config." >&2
  exit 1
fi
while read oldrev newrev refname; do
  if [ "$oldrev" = "0000000000000000000000000000000000000000" ]; then
    # dammit git
    zwrite -c "$class" -i "${instance:-${refname#refs/heads/}}" -s "$zsig: $refname" -d \
      -m "New branch $refname created, currently at $newrev."
    continue
  fi
  git rev-list --first-parent --reverse "$oldrev..$newrev" | while read rev; do
    shortrev=`git log -1 --pretty=format:%h "$rev"`
    (git show --stat -M $usecolor "$rev" |
     sed -e 's/@/@@/g' \
         -e 's/}/@(})/g' \
         -e 's/\[m/}@{/g' \
         -e 's/\[33m/@color(yellow)/g' \
         -e 's/\[31m/@color(red)/g' \
         -e 's/\[32m/@color(green)/g' \
         -e '1s/^/@{/' \
         -e '$s/$/}/') |
    zwrite -c "$class" -i "${instance:-$shortrev}" -s "$zsig: $refname" -d
  done
done
