#!/bin/bash
#
# This script is run after receive-pack has accepted a pack and the
# repository has been updated.  It is passed arguments in through stdin
# in the form
#  <oldrev> <newrev> <refname>
# For example:
#  aa453216d1b3e49e7f6f98441fa56946ddcd6a20 68f7abf4e6f922807889f52bc043ecd31b79f814 refs/heads/master

class=`git config zephyr.class`
instance=`git config zephyr.instance`
zsig=`git config zephyr.zsig`
color=`git config --bool zephyr.color`
maxlines=`git config --int zephyr.maxlines 2>/dev/null || echo 50`

if [ "${color:-true}" = "true" ]; then
    usecolor="--color"
else
    usecolor=""
fi

if [ -z "$zsig" ]; then
    if [ -e "$GIT_DIR/description" ]; then
        zsig=`cat "$GIT_DIR/description"`
    fi
    if [ -z "$zsig" ] || \
        [ "$zsig" = "Unnamed repository; edit this file to name it for gitweb." ] || \
        [ "$zsig" = "Unnamed repository; edit this file 'description' to name the repository." ]; then
        zsig=$(basename "$(cd "$GIT_DIR" && pwd)")
        if [ "$zsig" = ".git" ]; then
            zsig=$(basename "$(cd "$GIT_DIR/.." && pwd)")
        fi
    fi
fi

if [ -z "$class" ]; then
  echo "I don't know where to send a commit zephyr!" >&2
  echo "Please set the zephyr.class config variable in" >&2
  echo "$PWD/config." >&2
  exit 1
fi

let max=10
check_max () {
  if ! let --max; then
    zwrite -c "$class" -i "${instance:-git}" -s "Aperture Science Emergency Intelligence Incinerator" -d \
      -m 'Aborting zephyr hook to prevent zwrite flood.'
    exit 0
  fi
}

while read oldrev newrev refname; do
  if [ "$oldrev" = "0000000000000000000000000000000000000000" ]; then
    check_max
    # dammit git
    zwrite -c "$class" -i "${instance:-${refname#refs/heads/}}" -s "$zsig: $refname" -d \
      -m "New branch $refname created, currently at $newrev."
    continue
  fi
  while read rev; do
    check_max
    shortrev=`git log -1 --pretty=format:%h "$rev"`
    lines=`git show -M "$rev" | wc -l`
    cmd="git show --stat -M $usecolor $rev"
    if [ $lines -lt $maxlines ]; then
	cmd="git show -M $usecolor $rev"
    fi
    ($cmd |
     sed -e 's/@/@@/g' \
         -e 's/}/@(})/g' \
         -e 's/\[m/}@{/g' \
	 -e 's/\[1m/}@b{/g' \
         -e 's/\[33m/@color(yellow)/g' \
         -e 's/\[31m/@color(red)/g' \
         -e 's/\[32m/@color(green)/g' \
         -e 's/\[36m/@color(cyan)/g' \
         -e '1s/^/@{/' \
         -e '$s/$/}/') |
    zwrite -c "$class" -i "${instance:-$shortrev}" -s "$zsig: $refname" -d
  done < <(git rev-list --first-parent --reverse "$oldrev..$newrev")
done
