#!/bin/sh
# This is a trivial wrapper around git-cvsimport.

dir="$1"
shift
if [ -z "$dir" ]; then
  echo "Usage: git-rcsimport path/to/dir"
  exit 1
fi
if [ ! -d "$dir/RCS" ]; then
  echo "$dir/RCS does not exist."
  exit 1
fi

tmpdir=`mktemp -d -t git-rcsimport`
mkdir "$tmpdir/CVSROOT" "$tmpdir/locks" "$tmpdir/rcs"
echo "LockDir=$tmpdir/locks" > "$tmpdir/CVSROOT/config"
absdir=`cd "$dir"; pwd`
(cd "$absdir"; find . -name RCS -type d) | while read dir; do
    rcsdir=$tmpdir/rcs/`dirname "$dir"`
    mkdir -p "$rcsdir"
    ln -s "$absdir/$dir"/* "$rcsdir"
done
CVSROOT="$tmpdir" git cvsimport "$@" rcs
rm -r "$tmpdir"
